#Improve your self

import types
import logging


class Helper:
    def __init__(self): ...


class Logger:
    def __init__(self, log_level: str, log_path: str): ...
    
    def set_formatter(self, str_formatter: str) -> logging.Formatter: ...
    
    def set_level(self) -> Union[logging.INFO, logging.DEBUG, logging.WARNING, logging.ERROR, logging.CRITICAL]: ...


class NotFoundMode(Exception):
    def __init__(self, info): ...


class SysArgError(Exception):
    def __init__(self, info_error): ...


class LogLevelError(Exception):
    def __init__(self, info_error): ...


class Encrypt:
    def __init__(self): ...

    def turn_(self, string: str, num_of_turn): ...

    def encode(self, input_string: str, key: str): ...

    def decode(self, some_string: str, key: int): ...

    def crypto(self, string: str, key: str): ...

    def hash(str_data: str) -> str: ...

    def is_true(try_data: str, hash_: str)  -> bool: ...

    def reverse_func(self, lst: list) -> list: ...

    def translate__from_2__to_10(self, num: Union[int, str]) -> int: ...


class CreateTable:
    def __init__(self, table_name: str, str_request: str, cursor, db, DB: str): ...


class ConnectDB:

    def __init__(self, DB: str, dbname: str, user: str, password: str, host: str, port: int): ...

    def create(self) -> int: ...

    def select(self, mode: int, fetch: str, search_data: str, table_name: str, each_column: str, char: str, by_: str) -> Union[list, tuple]: ...

    def delete(self, table_name: str, each_column: str, char: str, by_: str) -> int: ...

    def update(self, table_name: str, column_name: str, value: Union[int, str, bool, float, set, list, dict, tuple], each_column: str, char: str, by_: Union[int, str, bool, float]) -> int: ...

    def insert(self, table_name: str, columns_name: str, columns_datas: Union[int, str, bool, float, set, list, dict, tuple]) -> int: ...


#The end