from types import Union


class MTest:
    def __init__(self, logging: bool, show_info: bool): ...

    def checkEqual(self, data_one: Union[int, float, str, bool, set, list, dict], result: Union[int, float, str, bool, set, list, dict]): ...

    def checkNotEqual(self, data_one: Union[int, float, str, bool, set, list, dict], result: Union[int, float, str, bool, set, list, dict]): ...

    def checkTrue(self, data_one: bool): ...

    def checkFalse(self, data_one: bool): ...

    def checkIn(self, data: Union[int, float, str, bool, set, list, dict], some_list: Union[str, set, list]): ...

    def checkNotIn(self, data: Union[int, float, str, bool, set, list, dict], some_list: Union[str, set, list]): ...

    def checkIs(self, data: Union[int, float, str, bool, set, list, dict], result: Union[int, float, str, bool, set, list, dict]): ...

    def checkNotIs(self, data: Union[int, float, str, bool, set, list, dict], result: Union[int, float, str, bool, set, list, dict]): ...

    def checkNone(self, data: Union[int, float, str, bool, set, list, dict]): ...

    def checkPositiveNumber(self, number: Union[int, float]): ...

    def checkNegativeNumber(self, number: Union[int, float]): ...

    def checkA_Less_B(self, a: Union[int, float], b: Union[int, float]): ...

    def checkA_More_B(self, a: Union[int, float], b: Union[int, float]): ...

    def results(self) -> str: ...